### ISSUE TITLE
How to access from the outside

### ISSUE THREAD

**Issue by ShengShiQAQ** [nebula-codes/sitservercontroller#1]

**Comment by nebula-codes** [comment]
The listening ip is set to all. To access it from outside, you would need your port forwarding to be done.

**Comment by ShengShiQAQ** [comment]
I don't know how to set it up

**Comment by ShengShiQAQ** [comment]
> 侦听 ip 设置为全部。要从外部访问它，您需要完成端口转发。

I don't know how to set it up
