### ISSUE TITLE
How to access from the outside

### ISSUE THREAD

**Issue by ShengShiQAQ** [nebula-codes/sitservercontroller#2]
I've tried for a long time, but I still don't figure out how to do it
![image](https://github.com/nebula-codes/sitservercontroller/assets/91988874/cbd4600a-6fa9-4e74-b5d6-96459919258f)

**Comment by nebula-codes** [comment]
That is a functional web server. If you are unable to access it from the outside, its your port forwarding. Open a browser locally at the IP of the web server and itll work. use http://localhost:6969 for local usage.
